### ISSUE TITLE
please document how to set client id/secret

### ISSUE THREAD

**Issue by wchristian** [alin-rautoiu/mastodroid#23]
Right now they are just grabbed as empty strings, which obviously doesn't work. Please put some guidance in the readme how to set that up properly.

**Comment by charlag** [comment]
Yeah, we should, thanks for pointing that out.
To register an app, please see `POST /api/v1/apps`  from here https://github.com/tootsuite/mastodon/blob/master/docs/Using-the-API/API.md

Then paste them them in to the src/main/res/values/secret.xml

**Comment by Gargron** [comment]
The app registering should be done by the app itself, when a user logins to a server for the first time

**Comment by charlag** [comment]
In the future we should make them dynamic because we should support different instances as @Gargron said. We should ask user for their instance and make that /api/v1/apps request from the app.

**Comment by wchristian** [comment]
Ah, thanks for explaining. Also, hrm, i feel there should be a way to do this in a file that isn't checked into source control.

**Comment by wchristian** [comment]
@Gargron So the id/secret should be unique per app install? Or unique per user + app install?

**Comment by Gargron** [comment]
It's unique per app install + domain

**Comment by charlag** [comment]
Should we close it? @wchristian

**Comment by wchristian** [comment]
@charlag I think until the proper secret-getting mechanism is implemented there should still be a note in the README to help new developers onboard smoother. Up to you whether you'd like to do that, or just close this directly.
